import type {
  User,
  Organization,
  Youth,
  Masul,
  IndividualPlan,
  Meeting,
  CompletedWork,
  ToshkentDistrict,
} from "./types";

import { TOSHKENT_VILOYATI_DISTRICTS } from "./types";

// Users with district assignments
export const mockUsers: User[] = [
  {
    id: "1",
    fullName: "Abdullayev Sardor",
    email: "admin@yoshlar.uz",
    role: "admin",
    avatar: "",
    createdAt: "2024-01-01",
  },
  {
    id: "2",
    fullName: "Karimov Jamshid",
    email: "direktor@yoshlar.uz",
    role: "direktor",
    avatar: "",
    createdAt: "2024-01-01",
  },
  {
    id: "3",
    fullName: "Rahimov Bekzod",
    email: "bekobod@yoshlar.uz",
    role: "tashkilot_direktori",
    organizationId: "org1",
    organizationName: "Bekobod tumani yoshlar markazi",
    districtId: "Bekobod tumani",
    avatar: "",
    createdAt: "2024-01-15",
  },
  {
    id: "4",
    fullName: "Saidov Anvar",
    email: "masul1@yoshlar.uz",
    role: "masul_hodim",
    organizationId: "org1",
    organizationName: "Bekobod tumani yoshlar markazi",
    districtId: "Bekobod tumani",
    avatar: "",
    createdAt: "2024-02-01",
  },
  {
    id: "5",
    fullName: "Toshmatov Dilshod",
    email: "moderator@yoshlar.uz",
    role: "moderator",
    avatar: "",
    createdAt: "2024-01-10",
  },
  {
    id: "6",
    fullName: "Xolmatov Rustam",
    email: "chinoz@yoshlar.uz",
    role: "tashkilot_direktori",
    organizationId: "org2",
    organizationName: "Chinoz tumani yoshlar markazi",
    districtId: "Chinoz tumani",
    avatar: "",
    createdAt: "2024-01-20",
  },
  {
    id: "7",
    fullName: "Nazarov Ulug'bek",
    email: "qibray@yoshlar.uz",
    role: "tashkilot_direktori",
    organizationId: "org3",
    organizationName: "Qibray tumani yoshlar markazi",
    districtId: "Qibray tumani",
    avatar: "",
    createdAt: "2024-02-01",
  },
  {
    id: "8",
    fullName: "Ergashev Oybek",
    email: "parkent@yoshlar.uz",
    role: "tashkilot_direktori",
    organizationId: "org4",
    organizationName: "Parkent tumani yoshlar markazi",
    districtId: "Parkent tumani",
    avatar: "",
    createdAt: "2024-02-10",
  },
  {
    id: "9",
    fullName: "Mahmudov Javlon",
    email: "zangiota@yoshlar.uz",
    role: "tashkilot_direktori",
    organizationId: "org5",
    organizationName: "Zangiota tumani yoshlar markazi",
    districtId: "Zangiota tumani",
    avatar: "",
    createdAt: "2024-02-15",
  },
];

// Organizations - one per district (14 districts)
export const mockOrganizations: Organization[] = [
  {
    id: "org1",
    name: "Bekobod tumani yoshlar markazi",
    districtId: "Bekobod tumani",
    address: "Bekobod shahri, Mustaqillik ko'chasi, 15",
    directorId: "3",
    directorName: "Rahimov Bekzod",
    masullarCount: 8,
    yoshlarCount: 45,
    createdAt: "2024-01-15",
  },
  {
    id: "org2",
    name: "Chinoz tumani yoshlar markazi",
    districtId: "Chinoz tumani",
    address: "Chinoz shahri, Navoiy ko'chasi, 23",
    directorId: "6",
    directorName: "Xolmatov Rustam",
    masullarCount: 6,
    yoshlarCount: 38,
    createdAt: "2024-01-20",
  },
  {
    id: "org3",
    name: "Qibray tumani yoshlar markazi",
    districtId: "Qibray tumani",
    address: "Qibray, Amir Temur ko'chasi, 45",
    directorId: "7",
    directorName: "Nazarov Ulug'bek",
    masullarCount: 7,
    yoshlarCount: 52,
    createdAt: "2024-02-01",
  },
  {
    id: "org4",
    name: "Parkent tumani yoshlar markazi",
    districtId: "Parkent tumani",
    address: "Parkent shahri, Bobur ko'chasi, 67",
    directorId: "8",
    directorName: "Ergashev Oybek",
    masullarCount: 5,
    yoshlarCount: 34,
    createdAt: "2024-02-10",
  },
  {
    id: "org5",
    name: "Zangiota tumani yoshlar markazi",
    districtId: "Zangiota tumani",
    address: "Zangiota, Buyuk Ipak Yo'li ko'chasi, 89",
    directorId: "9",
    directorName: "Mahmudov Javlon",
    masullarCount: 9,
    yoshlarCount: 67,
    createdAt: "2024-02-15",
  },
  {
    id: "org6",
    name: "Bo'ka tumani yoshlar markazi",
    districtId: "Bo'ka tumani",
    address: "Bo'ka, Markaziy ko'chasi, 12",
    directorId: "10",
    directorName: "Qodirov Sherzod",
    masullarCount: 4,
    yoshlarCount: 28,
    createdAt: "2024-02-20",
  },
  {
    id: "org7",
    name: "Bo'stonliq tumani yoshlar markazi",
    districtId: "Bo'stonliq tumani",
    address: "Gazalkent, Tog' ko'chasi, 5",
    directorId: "11",
    directorName: "Normurodov Jahongir",
    masullarCount: 6,
    yoshlarCount: 41,
    createdAt: "2024-02-25",
  },
  {
    id: "org8",
    name: "Ohangaron tumani yoshlar markazi",
    districtId: "Ohangaron tumani",
    address: "Ohangaron shahri, Sanoat ko'chasi, 78",
    directorId: "12",
    directorName: "Toshmatov Sardor",
    masullarCount: 7,
    yoshlarCount: 56,
    createdAt: "2024-03-01",
  },
  {
    id: "org9",
    name: "Oqqo'rg'on tumani yoshlar markazi",
    districtId: "Oqqo'rg'on tumani",
    address: "Oqqo'rg'on, Qo'rg'on ko'chasi, 34",
    directorId: "13",
    directorName: "Abdullayev Jasur",
    masullarCount: 5,
    yoshlarCount: 32,
    createdAt: "2024-03-05",
  },
  {
    id: "org10",
    name: "Piskent tumani yoshlar markazi",
    districtId: "Piskent tumani",
    address: "Piskent, Dehqon ko'chasi, 56",
    directorId: "14",
    directorName: "Yusupov Bobur",
    masullarCount: 4,
    yoshlarCount: 26,
    createdAt: "2024-03-10",
  },
  {
    id: "org11",
    name: "Quyi Chirchiq tumani yoshlar markazi",
    districtId: "Quyi Chirchiq tumani",
    address: "Do'stobod, Chirchiq ko'chasi, 90",
    directorId: "15",
    directorName: "Rahmatov Sardor",
    masullarCount: 6,
    yoshlarCount: 44,
    createdAt: "2024-03-15",
  },
  {
    id: "org12",
    name: "Yangiyo'l tumani yoshlar markazi",
    districtId: "Yangiyo'l tumani",
    address: "Yangiyo'l shahri, Yangi ko'chasi, 101",
    directorId: "16",
    directorName: "Kamolov Dilshod",
    masullarCount: 8,
    yoshlarCount: 58,
    createdAt: "2024-03-20",
  },
  {
    id: "org13",
    name: "Yuqori Chirchiq tumani yoshlar markazi",
    districtId: "Yuqori Chirchiq tumani",
    address: "Chirchiq shahri, Yuqori ko'chasi, 112",
    directorId: "17",
    directorName: "Sodiqov Aziz",
    masullarCount: 5,
    yoshlarCount: 35,
    createdAt: "2024-03-25",
  },
  {
    id: "org14",
    name: "Toshkent tumani yoshlar markazi",
    districtId: "Toshkent tumani",
    address: "Keles, Toshkent ko'chasi, 1",
    directorId: "18",
    directorName: "Xolmatova Madina",
    masullarCount: 7,
    yoshlarCount: 49,
    createdAt: "2024-04-01",
  },
];

// Youth with district assignments
export const mockYouth: Youth[] = [
  // Bekobod tumani
  {
    id: "y1",
    fullName: "Aliyev Jasur",
    birthDate: "2002-05-15",
    address: "Bekobod shahri, Mustaqillik MFY",
    districtId: "Bekobod tumani",
    phone: "+998901234567",
    category: "Ijtimoiy himoya",
    status: "active",
    assignedMasulId: "4",
    assignedMasulName: "Saidov Anvar",
    organizationId: "org1",
    organizationName: "Bekobod tumani yoshlar markazi",
    aiScore: 78,
    plansCount: 3,
    meetingsCount: 8,
    createdAt: "2024-03-01",
  },
  {
    id: "y2",
    fullName: "Rahmonov Dilshod",
    birthDate: "2001-08-22",
    address: "Bekobod shahri, Yangi hayot MFY",
    districtId: "Bekobod tumani",
    phone: "+998901234568",
    category: "Ta'lim",
    status: "active",
    assignedMasulId: "4",
    assignedMasulName: "Saidov Anvar",
    organizationId: "org1",
    organizationName: "Bekobod tumani yoshlar markazi",
    aiScore: 85,
    plansCount: 4,
    meetingsCount: 12,
    createdAt: "2024-03-05",
  },
  // Chinoz tumani
  {
    id: "y3",
    fullName: "Karimova Nilufar",
    birthDate: "2003-02-10",
    address: "Chinoz shahri, Navoiy MFY",
    districtId: "Chinoz tumani",
    phone: "+998901234569",
    category: "Bandlik",
    status: "active",
    assignedMasulId: "m2",
    assignedMasulName: "Yusupov Bobur",
    organizationId: "org2",
    organizationName: "Chinoz tumani yoshlar markazi",
    aiScore: 72,
    plansCount: 2,
    meetingsCount: 6,
    createdAt: "2024-03-10",
  },
  {
    id: "y4",
    fullName: "Sodiqov Aziz",
    birthDate: "2000-11-30",
    address: "Chinoz shahri, Bog'bon MFY",
    districtId: "Chinoz tumani",
    phone: "+998901234570",
    category: "Huquqiy yordam",
    status: "graduated",
    assignedMasulId: "m2",
    assignedMasulName: "Yusupov Bobur",
    organizationId: "org2",
    organizationName: "Chinoz tumani yoshlar markazi",
    aiScore: 92,
    plansCount: 5,
    meetingsCount: 15,
    createdAt: "2024-01-20",
  },
  // Qibray tumani
  {
    id: "y5",
    fullName: "Tursunov Javohir",
    birthDate: "2002-07-18",
    address: "Qibray, Yashnaobod MFY",
    districtId: "Qibray tumani",
    phone: "+998901234571",
    category: "Psixologik yordam",
    status: "active",
    assignedMasulId: "m3",
    assignedMasulName: "Qodirov Sherzod",
    organizationId: "org3",
    organizationName: "Qibray tumani yoshlar markazi",
    aiScore: 68,
    plansCount: 2,
    meetingsCount: 5,
    createdAt: "2024-04-01",
  },
  {
    id: "y6",
    fullName: "Xolmatova Madina",
    birthDate: "2001-04-25",
    address: "Qibray, Gulbahor MFY",
    districtId: "Qibray tumani",
    phone: "+998901234572",
    category: "Ta'lim",
    status: "active",
    aiScore: 75,
    plansCount: 3,
    meetingsCount: 7,
    createdAt: "2024-04-05",
  },
  // Parkent tumani
  {
    id: "y7",
    fullName: "Normatov Shoxrux",
    birthDate: "2002-01-12",
    address: "Parkent, Markaziy MFY",
    districtId: "Parkent tumani",
    phone: "+998901234573",
    category: "Bandlik",
    status: "active",
    assignedMasulId: "m4",
    assignedMasulName: "Rahmatov Sardor",
    organizationId: "org4",
    organizationName: "Parkent tumani yoshlar markazi",
    aiScore: 80,
    plansCount: 4,
    meetingsCount: 10,
    createdAt: "2024-04-10",
  },
  // Zangiota tumani
  {
    id: "y8",
    fullName: "Akbarov Temur",
    birthDate: "2001-09-05",
    address: "Zangiota, Ipak yo'li MFY",
    districtId: "Zangiota tumani",
    phone: "+998901234574",
    category: "Sog'liqni saqlash",
    status: "active",
    assignedMasulId: "m5",
    assignedMasulName: "Normurodov Jahongir",
    organizationId: "org5",
    organizationName: "Zangiota tumani yoshlar markazi",
    aiScore: 65,
    plansCount: 1,
    meetingsCount: 4,
    createdAt: "2024-04-15",
  },
  {
    id: "y9",
    fullName: "Mirzayeva Zulfiya",
    birthDate: "2003-03-20",
    address: "Zangiota, Oqtepa MFY",
    districtId: "Zangiota tumani",
    phone: "+998901234575",
    category: "Oilaviy muammolar",
    status: "active",
    assignedMasulId: "m5",
    assignedMasulName: "Normurodov Jahongir",
    organizationId: "org5",
    organizationName: "Zangiota tumani yoshlar markazi",
    aiScore: 70,
    plansCount: 2,
    meetingsCount: 6,
    createdAt: "2024-04-20",
  },
  // Bo'ka tumani
  {
    id: "y10",
    fullName: "Qosimov Sardor",
    birthDate: "2002-06-08",
    address: "Bo'ka, Markaziy MFY",
    districtId: "Bo'ka tumani",
    phone: "+998901234576",
    category: "Uy-joy muammolari",
    status: "active",
    aiScore: 73,
    plansCount: 2,
    meetingsCount: 5,
    createdAt: "2024-04-25",
  },
  // Bo'stonliq tumani
  {
    id: "y11",
    fullName: "Jumaboyev Asror",
    birthDate: "2001-12-14",
    address: "Gazalkent, Tog' MFY",
    districtId: "Bo'stonliq tumani",
    phone: "+998901234577",
    category: "Ta'lim",
    status: "active",
    aiScore: 88,
    plansCount: 5,
    meetingsCount: 14,
    createdAt: "2024-05-01",
  },
  // Ohangaron tumani
  {
    id: "y12",
    fullName: "Toshpulatov Baxrom",
    birthDate: "2000-10-25",
    address: "Ohangaron, Sanoat MFY",
    districtId: "Ohangaron tumani",
    phone: "+998901234578",
    category: "Bandlik",
    status: "active",
    aiScore: 82,
    plansCount: 4,
    meetingsCount: 11,
    createdAt: "2024-05-05",
  },
  // Oqqo'rg'on tumani
  {
    id: "y13",
    fullName: "Xudoyberdiyev Nodir",
    birthDate: "2002-04-17",
    address: "Oqqo'rg'on, Qo'rg'on MFY",
    districtId: "Oqqo'rg'on tumani",
    phone: "+998901234579",
    category: "Huquqiy yordam",
    status: "active",
    aiScore: 77,
    plansCount: 3,
    meetingsCount: 8,
    createdAt: "2024-05-10",
  },
  // Yangiyo'l tumani
  {
    id: "y14",
    fullName: "Ergasheva Gulnora",
    birthDate: "2003-07-30",
    address: "Yangiyo'l, Yangi MFY",
    districtId: "Yangiyo'l tumani",
    phone: "+998901234580",
    category: "Ijtimoiy himoya",
    status: "active",
    aiScore: 79,
    plansCount: 3,
    meetingsCount: 9,
    createdAt: "2024-05-15",
  },
  // Toshkent tumani
  {
    id: "y15",
    fullName: "Raxmatullayev Bekzod",
    birthDate: "2001-11-08",
    address: "Keles, Toshkent MFY",
    districtId: "Toshkent tumani",
    phone: "+998901234581",
    category: "Psixologik yordam",
    status: "active",
    aiScore: 71,
    plansCount: 2,
    meetingsCount: 5,
    createdAt: "2024-05-20",
  },
];

// Mas'ullar with district assignments
export const mockMasullar: Masul[] = [
  {
    id: "4",
    fullName: "Saidov Anvar",
    email: "masul1@yoshlar.uz",
    phone: "+998901111111",
    districtId: "Bekobod tumani",
    organizationId: "org1",
    organizationName: "Bekobod tumani yoshlar markazi",
    assignedYouthCount: 15,
    completedPlansCount: 28,
    meetingsCount: 45,
    aiScore: 82,
    createdAt: "2024-02-01",
  },
  {
    id: "m2",
    fullName: "Yusupov Bobur",
    email: "masul2@yoshlar.uz",
    phone: "+998901111112",
    districtId: "Chinoz tumani",
    organizationId: "org2",
    organizationName: "Chinoz tumani yoshlar markazi",
    assignedYouthCount: 12,
    completedPlansCount: 22,
    meetingsCount: 38,
    aiScore: 76,
    createdAt: "2024-02-15",
  },
  {
    id: "m3",
    fullName: "Qodirov Sherzod",
    email: "masul3@yoshlar.uz",
    phone: "+998901111113",
    districtId: "Qibray tumani",
    organizationId: "org3",
    organizationName: "Qibray tumani yoshlar markazi",
    assignedYouthCount: 10,
    completedPlansCount: 35,
    meetingsCount: 52,
    aiScore: 89,
    createdAt: "2024-02-20",
  },
  {
    id: "m4",
    fullName: "Rahmatov Sardor",
    email: "masul4@yoshlar.uz",
    phone: "+998901111114",
    districtId: "Parkent tumani",
    organizationId: "org4",
    organizationName: "Parkent tumani yoshlar markazi",
    assignedYouthCount: 8,
    completedPlansCount: 18,
    meetingsCount: 32,
    aiScore: 79,
    createdAt: "2024-03-01",
  },
  {
    id: "m5",
    fullName: "Normurodov Jahongir",
    email: "masul5@yoshlar.uz",
    phone: "+998901111115",
    districtId: "Zangiota tumani",
    organizationId: "org5",
    organizationName: "Zangiota tumani yoshlar markazi",
    assignedYouthCount: 14,
    completedPlansCount: 25,
    meetingsCount: 40,
    aiScore: 74,
    createdAt: "2024-03-10",
  },
  {
    id: "m6",
    fullName: "Toshmatov Sardor",
    email: "masul6@yoshlar.uz",
    phone: "+998901111116",
    districtId: "Ohangaron tumani",
    organizationId: "org8",
    organizationName: "Ohangaron tumani yoshlar markazi",
    assignedYouthCount: 11,
    completedPlansCount: 20,
    meetingsCount: 35,
    aiScore: 81,
    createdAt: "2024-03-15",
  },
  {
    id: "m7",
    fullName: "Kamolov Dilshod",
    email: "masul7@yoshlar.uz",
    phone: "+998901111117",
    districtId: "Yangiyo'l tumani",
    organizationId: "org12",
    organizationName: "Yangiyo'l tumani yoshlar markazi",
    assignedYouthCount: 13,
    completedPlansCount: 24,
    meetingsCount: 42,
    aiScore: 85,
    createdAt: "2024-03-20",
  },
  {
    id: "m8",
    fullName: "Abdullayev Jasur",
    email: "masul8@yoshlar.uz",
    phone: "+998901111118",
    districtId: "Bo'stonliq tumani",
    organizationId: "org7",
    organizationName: "Bo'stonliq tumani yoshlar markazi",
    assignedYouthCount: 9,
    completedPlansCount: 16,
    meetingsCount: 28,
    aiScore: 77,
    createdAt: "2024-03-25",
  },
];

// Individual Plans
export const mockPlans: IndividualPlan[] = [
  {
    id: "p1",
    youthId: "y1",
    youthName: "Aliyev Jasur",
    masulId: "4",
    masulName: "Saidov Anvar",
    title: "Kasb-hunar o'rgatish dasturi",
    description: "Kompyuter savodxonligi va dasturlash asoslarini o'rgatish",
    startDate: "2024-03-15",
    endDate: "2024-06-15",
    status: "in_progress",
    progress: 65,
    createdAt: "2024-03-10",
  },
  {
    id: "p2",
    youthId: "y2",
    youthName: "Rahmonov Dilshod",
    masulId: "4",
    masulName: "Saidov Anvar",
    title: "Oliy ta'limga tayyorlov",
    description: "DTM testlariga tayyorgarlik ko'rish",
    startDate: "2024-04-01",
    endDate: "2024-07-01",
    status: "in_progress",
    progress: 45,
    createdAt: "2024-03-25",
  },
  {
    id: "p3",
    youthId: "y3",
    youthName: "Karimova Nilufar",
    masulId: "m2",
    masulName: "Yusupov Bobur",
    title: "Ish bilan ta'minlash",
    description: "Mehnat birjasi orqali ish topish",
    startDate: "2024-03-20",
    endDate: "2024-05-20",
    status: "completed",
    progress: 100,
    createdAt: "2024-03-15",
  },
  {
    id: "p4",
    youthId: "y4",
    youthName: "Sodiqov Aziz",
    masulId: "m2",
    masulName: "Yusupov Bobur",
    title: "Huquqiy maslahat",
    description: "Hujjatlarni rasmiylashtirishda yordam",
    startDate: "2024-02-01",
    endDate: "2024-03-01",
    status: "completed",
    progress: 100,
    createdAt: "2024-01-25",
  },
  {
    id: "p5",
    youthId: "y5",
    youthName: "Tursunov Javohir",
    masulId: "m3",
    masulName: "Qodirov Sherzod",
    title: "Psixologik reabilitatsiya",
    description: "Individual va guruhiy mashg'ulotlar",
    startDate: "2024-04-10",
    endDate: "2024-07-10",
    status: "planned",
    progress: 0,
    createdAt: "2024-04-05",
  },
  {
    id: "p6",
    youthId: "y7",
    youthName: "Normatov Shoxrux",
    masulId: "m4",
    masulName: "Rahmatov Sardor",
    title: "Tadbirkorlikka tayyorlov",
    description: "Kichik biznes asoslarini o'rgatish",
    startDate: "2024-04-15",
    endDate: "2024-07-15",
    status: "in_progress",
    progress: 30,
    createdAt: "2024-04-10",
  },
  {
    id: "p7",
    youthId: "y8",
    youthName: "Akbarov Temur",
    masulId: "m5",
    masulName: "Normurodov Jahongir",
    title: "Sog'liqni tiklash dasturi",
    description: "Tibbiy ko'rik va davolash",
    startDate: "2024-04-20",
    endDate: "2024-08-20",
    status: "in_progress",
    progress: 25,
    createdAt: "2024-04-15",
  },
];

// Meetings
export const mockMeetings: Meeting[] = [
  {
    id: "m1",
    youthId: "y1",
    youthName: "Aliyev Jasur",
    masulId: "4",
    masulName: "Saidov Anvar",
    title: "Dastlabki tanishish",
    description: "Yoshlik holati va ehtiyojlarini aniqlash",
    date: "2024-03-05",
    location: "Bekobod tumani yoshlar markazi",
    status: "completed",
    notes: "Yosh kompyuter sohasiga qiziqishi bor",
    createdAt: "2024-03-01",
  },
  {
    id: "m2",
    youthId: "y1",
    youthName: "Aliyev Jasur",
    masulId: "4",
    masulName: "Saidov Anvar",
    title: "O'quv jarayoni monitoring",
    description: "Kurs davomidagi yutuqlarni baholash",
    date: "2024-04-15",
    location: "Bekobod IT markazi",
    status: "completed",
    notes: "HTML va CSS asoslarini o'zlashtirdi",
    createdAt: "2024-04-10",
  },
  {
    id: "m3",
    youthId: "y2",
    youthName: "Rahmonov Dilshod",
    masulId: "4",
    masulName: "Saidov Anvar",
    title: "Ta'lim rejasi muhokamasi",
    description: "OTM tanlash va tayyorgarlik rejasi",
    date: "2024-04-20",
    location: "Bekobod tumani yoshlar markazi",
    status: "scheduled",
    createdAt: "2024-04-15",
  },
  {
    id: "m4",
    youthId: "y3",
    youthName: "Karimova Nilufar",
    masulId: "m2",
    masulName: "Yusupov Bobur",
    title: "Ish suhbatiga tayyorgarlik",
    description: "Resume yozish va suhbat ko'nikmalari",
    date: "2024-04-10",
    location: "Chinoz mehnat birjasi",
    status: "completed",
    notes: "Muvaffaqiyatli suhbatdan o'tdi",
    createdAt: "2024-04-05",
  },
  {
    id: "m5",
    youthId: "y5",
    youthName: "Tursunov Javohir",
    masulId: "m3",
    masulName: "Qodirov Sherzod",
    title: "Psixolog bilan uchrashuv",
    description: "Boshlang'ich psixologik baholash",
    date: "2024-04-12",
    location: "Qibray tumani yoshlar markazi",
    status: "completed",
    notes: "Muntazam mashg'ulotlar tavsiya etildi",
    createdAt: "2024-04-08",
  },
  {
    id: "m6",
    youthId: "y7",
    youthName: "Normatov Shoxrux",
    masulId: "m4",
    masulName: "Rahmatov Sardor",
    title: "Biznes-reja taqdimoti",
    description: "Yosh o'z biznes g'oyasini taqdim etadi",
    date: "2024-05-01",
    location: "Parkent tumani yoshlar markazi",
    status: "scheduled",
    createdAt: "2024-04-25",
  },
];

// Completed Works
export const mockCompletedWorks: CompletedWork[] = [
  {
    id: "w1",
    youthId: "y1",
    youthName: "Aliyev Jasur",
    masulId: "4",
    masulName: "Saidov Anvar",
    planId: "p1",
    title: "HTML/CSS kursi yakunlandi",
    description: "Frontend asoslari kursi muvaffaqiyatli yakunlandi",
    date: "2024-04-20",
    result: "Sertifikat olindi",
    createdAt: "2024-04-20",
  },
  {
    id: "w2",
    youthId: "y3",
    youthName: "Karimova Nilufar",
    masulId: "m2",
    masulName: "Yusupov Bobur",
    planId: "p3",
    title: "Ishga joylashtirildi",
    description: "Mahalliy kompaniyada operator lavozimiga qabul qilindi",
    date: "2024-05-15",
    result: "Doimiy ish topildi",
    createdAt: "2024-05-15",
  },
  {
    id: "w3",
    youthId: "y4",
    youthName: "Sodiqov Aziz",
    masulId: "m2",
    masulName: "Yusupov Bobur",
    planId: "p4",
    title: "Hujjatlar rasmiylashtirildi",
    description: "Barcha kerakli hujjatlar qonuniy tartibda rasmiylashtirildi",
    date: "2024-03-01",
    result: "Hujjatlar tayyor",
    createdAt: "2024-03-01",
  },
];

// Categories
export const youthCategories = [
  "Ijtimoiy himoya",
  "Ta'lim",
  "Bandlik",
  "Huquqiy yordam",
  "Psixologik yordam",
  "Sog'liqni saqlash",
  "Uy-joy muammolari",
  "Oilaviy muammolar",
];

// District color map for badges
export const districtColors: Record<ToshkentDistrict, string> = {
  "Bekobod tumani": "bg-blue-100 text-blue-800",
  "Bo'ka tumani": "bg-green-100 text-green-800",
  "Bo'stonliq tumani": "bg-emerald-100 text-emerald-800",
  "Chinoz tumani": "bg-amber-100 text-amber-800",
  "Qibray tumani": "bg-orange-100 text-orange-800",
  "Ohangaron tumani": "bg-red-100 text-red-800",
  "Oqqo'rg'on tumani": "bg-pink-100 text-pink-800",
  "Parkent tumani": "bg-purple-100 text-purple-800",
  "Piskent tumani": "bg-indigo-100 text-indigo-800",
  "Quyi Chirchiq tumani": "bg-cyan-100 text-cyan-800",
  "Yangiyo'l tumani": "bg-teal-100 text-teal-800",
  "Yuqori Chirchiq tumani": "bg-sky-100 text-sky-800",
  "Zangiota tumani": "bg-lime-100 text-lime-800",
  "Toshkent tumani": "bg-slate-100 text-slate-800",
};

// Helper to get all districts
export const getAllDistricts = () => TOSHKENT_VILOYATI_DISTRICTS;
